### PR TITLE
Fix font flicker/load times on staging

### PR DESCRIPTION
**Pull request by caseycesari**
## Overview

Reduces the flickering/load times on staging by doing the following:

- **Ensure fonts are only requested once.** Due to a bug in Styled Components (styled-components/styled-components#1593), custom fonts were requested each time a component was mounted that referenced them. This resulted in the text on the site flickering when the fonts reloaded unnecessarily each time a new tab was clicked. One suggested workaround is to load the fonts through a CSS stylesheet, outside of the Styled Components pipeline. That workaround is implemented here.

- **Process images through webpack.** To reduce the number of resource requests, process the fish photos through webpack. This results in most of the images being Base64 encoded. These requests are faster and are cached. For some reason, with the current implementation, the images are requested each time the component is mounted. This does not happen when the images are processed through Webpack.

Connects #63

### Demo

See staging preview site.

### Notes

One of the main sources of the lag is the videos downloading. These requests block other requests because they are rather large. I've created a follow-up issue to try and lazy load the videos instead of loading them all at once on page load.

## Testing Instructions

- Compare the staging site to the build preview site for this PR, and verify the slowing and flickers that appear on staging are greatly reduced on the build preview branch.

### CODE REVIEW

**Review by maurizi — CHANGES_REQUESTED** [review]
Oof, it hurts that we have to do this, but this does seem like the best path forward.

I'd like to also revert the changes to the Webpack config and uninstall the copy plugin that were added here: https://github.com/azavea/pwd-fishway/pull/50/commits/efff2006fdf01c415dfc8fe97ad75f9d8152b079 . That will make sure that any other media references need to go through Webpack to work, so we don't accidentally cause more load time issues.

Also, don't forget to create this issue:
> I've created a follow-up issue to try and lazy load the videos instead of loading them all at once on page load.

**Comment by caseycesari** [comment]
@maurizi I'm happy to remove the copy plugin, but I think we still need it for the videos, right? I didn't process the videos through Webpack because, based on some googling, there didn't appear to be any advantage to it. I can change that though if you think it's an improvement.

**Comment by maurizi** [comment]
Ah, I missed that we hadn't switched the videos to be pulled in through Webpack as well.

If it doesn't _harm_ things, my preference would be to load the videos through Webpack as well, for simplicity, but I don't feel very strongly about it - I'll leave it up to you to decide.

**Review by maurizi — APPROVED** [review]

**Comment by caseycesari** [comment]
Updated the PR to process videos through Webpack. Going to merge.

**Pull request merged**
