### PR TITLE
Add basic screensaver component

### PR DESCRIPTION
**Pull request by fungjj92**
## Overview

This PR creates an initial screensaver component, as per wireframes. Minimal styling included in this PR, purposefully. In preparation for design to do work on the app, even though it was not specified in the original issue, I brought in [styled-components](https://www.styled-components.com/) which design plans on using.

Connects #11

### Demo

Screen Shot 2019-04-23 at 11 58 42 AM

### Notes

I also updated the Vagrantfile, which @maurizi you may recognize from Urban Apps, to use NFS for OSX only. On my Mac, and for some other Mac users, the standard VM  setup locks up mysteriously and frequently. The same NFS set up breaks the VM on Linux.

## Testing Instructions

`vagrant up && vagrant ssh`
`./scripts/server`
http://localhost:3474/

### CODE REVIEW

**Comment by fungjj92** [comment]
Hold off on review. I am ripping out SASS in favor of styled-components, which uses CSS.

**Comment by fungjj92** [comment]
Good to go 👍

**Comment by maurizi** [comment]
`vagrant up` wouldn't work for me, until I made the following change:

```diff
diff --git a/Vagrantfile b/Vagrantfile
index 8258c8e..5f5c996 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -7,6 +7,8 @@ FISHWAY_SHARED_FOLDER_TYPE = ENV.fetch("FISHWAY_SHARED_FOLDER_TYPE", "nfs")
 if FISHWAY_SHARED_FOLDER_TYPE == "nfs"
   if not Vagrant::Util::Platform.linux? then
     FISHWAY_MOUNT_OPTIONS = ['vers=3', 'udp', 'actimeo=1']
+  else
+    FISHWAY_MOUNT_OPTIONS = ['rw', 'vers=3', 'tcp', 'nolock', 'actimeo=1']
   end
 else
   if ENV.has_key?("FISHWAY_MOUNT_OPTIONS")
(END)
```

Additionally, when I first ran `scripts/update` I got the following error:
```
ERROR: Cannot start service app: error while creating mount source path '/vagrant/dist': chown /vagrant/dist: operation not permitted
```
Running it again ran into a different error:
```
ERROR: Cannot start service app: error while creating mount source path '/vagrant/src/nginx/srv/dist': chown /vagrant/src/nginx/srv/dist: operation not permitted
```
After that `scripts/update` was able to run successfully. If we add steps to `scripts/update` to create those directories or commit dummy files inside of them to the repository, that would fix those fresh provisioning issues.

**Review by maurizi — CHANGES_REQUESTED** [review]
This looks good, just need to get the changes to the `Vagrantfile` & something to handle those directory creation errors and this will be good to merge.

**Comment by fungjj92** [comment]
Thanks for the detailed bug report. I destroyed and rebuilt my VM, and setup was smooth. That said, I didn't have issues before and I'm running OSX, so I'm not the best judge. Will you pull down changes and try again?

**Review by maurizi — APPROVED** [review]
:+1:

**Pull request merged**
