### PR TITLE
Add button variants and FontAwesome Pro

### PR DESCRIPTION
**Pull request by alexelash**
## Overview
This PR tackles adding our button styles to the app:
- Primary (green, default)
- Secondary (sky blue)
- Close (white)
- Link

FontAwesome Pro has also been added to the app, but we will need to follow up with #64 so that it works with Netlify previews.

Connects #49, connects #61 

### Demo
Primary
Screen Shot 2019-05-13 at 4 45 39 PM
Primary on hover
button-on-click
Secondary
Screen Shot 2019-05-13 at 4 48 05 PM
Close icon
Screen Shot 2019-05-13 at 4 47 13 PM
Link
Screen Shot 2019-05-13 at 5 05 39 PM

### Notes
- While doing this, I cleaned up how I was handling Header and Text props, so pushed some styles to `defaultProps`. Now that this isn't being explicitly stated in the `variant`, we can more easily override things like color (this will be more relevant when we make the modal).
- We don't need to add buttons that specifically deal with icons (yay!) We get a lot of stuff for free from the imported `<FontAwesomeIcon>` component, including the ability to add the proper padding to a icon button with `pull: left|right`. Using this prop, we can make the following monstrosity:
Screen Shot 2019-05-13 at 3 29 55 PM More [here.](https://www.npmjs.com/package/@fortawesome/react-fontawesome#basic)

## Testing Instructions
* `git pull`
* Follow the new README instructions for adding a FontAwesome Pro token to the project.
* `./scripts/update`
* Look at Screensaver, and note that the default button is a Primary style. 
* Add `variant='secondary'` to the Screensaver button. Note that it is now the Secondary style.
* Add `variant='link`.
* Go to "Test your skills" and click the Play button. Note the Close button in the top right.

### CODE REVIEW

**Review by fungjj92 — APPROVED** [review]
Whoo! It's the start of something beautiful.

As discussed, I pushed up two commits that make token setting more robust and compatible with Netlify. Please go through the README and confirm setting up the token the new way works. We'll all need to add a `docker-compose.env` locally going forward.

**Comment by alexelash** [comment]
@fungjj92 I followed the steps in the README, but I'm getting this error:
```
error An unexpected error occurred: "Failed to replace env in config: ${FONT_AWESOME_PRO_TOKEN}".

**Comment by fungjj92** [comment]
Pushed up changes! As discussed, docker-compose used to auto-pick up `docker-compose.env` files but now requires an explicit instruction.

**Comment by alexelash** [comment]
Yep, working as expected now!

**Pull request merged**
